name: Update Links and Deploy

on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes
  push:
    branches:
      - main

jobs:
  update-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Use latest version

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Cache node modules
        uses: actions/cache@v3  # Use latest version
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install npm dependencies
        run: |
          if [ -f package.json ]; then
            echo "package.json found, installing dependencies..."
            npm install
          else
            echo "No package.json found. Installing manually..."
            npm install axios cheerio
          fi

      - name: Fetch and Update Links
        run: |
          node index-js/monopoly-go.js
          echo "Content of links-json/monopoly-go.json:"
          cat links-json/monopoly-go.json

      - name: Update Reward Page
        run: |
          echo '<div class="rewards">' > static/rewards/monopoly-go.md
          jq -r '.[] | "  <p><a href=\"" + .href + "\">" + .text + "</a></p>\n"' links-json/monopoly-go.json >> static/rewards/monopoly-go.md
          echo '</div>' >> static/rewards/monopoly-go.md
          echo "Content of static/rewards/monopoly-go.md:"
          cat static/rewards/monopoly-go.md

      - name: Configure Git
        run: |
          git config --global user.email "prolladmail@gmail.com"
          git config --global user.name "Prollad99"

      - name: Commit and Push changes
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        run: |
          git add static/rewards/monopoly-go.md links-json/monopoly-go.json
          git commit -m "Update monopoly-go reward links" || true

          # Pull with rebase to prevent conflicts
          git pull --rebase

          # Push changes with retries
          for i in {1..5}; do
            git push https://x-access-token:${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/Prollad99/mnply-go.git && break
            echo "Retry $i: Push failed, retrying in 5 seconds..."
            sleep 5
            git pull --rebase
          done